# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Flowers.create(name:'Carousel Dark Red', sixcount: 18, eightcount: 3, imagelink:'CarouselDarkRed.jpg')
Flowers.create(name:'Chianti Red', sixcount: 18, eightcount: 2, imagelink:'ChiantiRed.jpg')
Flowers.create(name:'Christmas Beauty Nostalgia', sixcount: 18, eightcount: 3, imagelink:'ChristmasBeautyNostalgia.jpg')
Flowers.create(name:'Christmas Feelings Pink', sixcount: 18, eightcount: 3, imagelink:'ChristmasFeelingsPink.jpg')
Flowers.create(name:'Christmas Feelings Red', sixcount: 18, eightcount: 3, imagelink:'ChristmasFeelingsRed.jpg')
Flowers.create(name:'Cinnamon Star', sixcount: 18, eightcount: 3, imagelink:'CinnamonStar.jpg')
Flowers.create(name:'Cortez White', sixcount: 18, eightcount: 3, imagelink:'CortezWhite.jpg')
Flowers.create(name:'Da Vinci', sixcount: 18, eightcount: 3, imagelink:'DaVinci.jpg')
Flowers.create(name:'Enduring Pink', sixcount: 18, eightcount: 3, imagelink:'EnduringPink.jpg')
Flowers.create(name:'Jester Red', sixcount: 18, eightcount: 2, imagelink:'JesterRed.jpg')
Flowers.create(name:'Marbella ', sixcount: 18, eightcount: 3, imagelink:'Marbella.jpg')
Flowers.create(name:'Marble Star', sixcount: 18, eightcount: 3, imagelink:'MarbleStar.jpg')
Flowers.create(name:'Maren', sixcount: 18, eightcount: 3, imagelink:'Maren.jpg')
Flowers.create(name:'Mars Marble', sixcount: 18, eightcount: 3, imagelink:'MarsMarble.jpg')
Flowers.create(name:'Mars Pink', sixcount: 17, eightcount: 2, imagelink:'MarsPink.jpg')
Flowers.create(name:'Mars Red', sixcount: 18, eightcount: 3, imagelink:'MarsRed.jpg')
Flowers.create(name:'Mars White', sixcount: 18, eightcount: 3, imagelink:'MarsWhite.jpg')
Flowers.create(name:'Monet', sixcount: 18, eightcount: 3, imagelink:'Monet.jpg')
Flowers.create(name:'Orion Red', sixcount: 18, eightcount: 2, imagelink:'OrionRed.jpg')
Flowers.create(name:'Peterstar Red', sixcount: 18, eightcount: 3, imagelink:'PeterstarRed.jpg')
Flowers.create(name:'Peterstar White', sixcount: 18, eightcount: 3, imagelink:'PeterstarWhite.jpg')
Flowers.create(name:'Prestige Maroon', sixcount: 18, eightcount: 3, imagelink:'PrestigeMaroon.jpg')
Flowers.create(name:'Red Glitter', sixcount: 18, eightcount: 3, imagelink:'RedGlitter.jpg')
Flowers.create(name:'Ruby Frost', sixcount: 18, eightcount: 2, imagelink:'RubyFrost.jpg')
Flowers.create(name:'Sonoro White Glitter', sixcount: 18, eightcount: 3, imagelink:'SonoroWhiteGlitter.jpg')
Flowers.create(name:'Sparkling Punch', sixcount: 16, eightcount: 3, imagelink:'SparklingPunch.jpg')
Flowers.create(name:"Strawberries 'n cream" , sixcount: 18, eightcount: 3, imagelink:'StrawberrynCream.jpg')
Flowers.create(name:'Tapestry', sixcount: 18, eightcount: 3, imagelink:'Tapestry.jpg')
Flowers.create(name:'Valentine', sixcount: 17, eightcount: 3, imagelink:'Valentine.jpg')
Flowers.create(name:'White Star', sixcount: 18, eightcount: 3, imagelink:'WhiteStar.jpg')
Flowers.create(name:'Winter Rose White', sixcount: 18, eightcount: 3, imagelink:'WinterRoseWhite.jpg')
Flowers.create(name:'Winter Sun White', sixcount: 18, eightcount: 3, imagelink:'WinterSunWhite.jpg')
